### ISSUE TITLE
announcing loco.rs

### ISSUE THREAD

**Issue by jondot** [film42/sidekiq-rs#34]
hi @film42 !
I just wanted to say thanks, sidekiq-rs has really helped motivate us to go all-in and build https://loco.rs/ -- a Rust on Rails framework, which uses sidekiq-rs as its background jobs framework!

Feel free to try Loco, and see how we integrated sidekiq-rs there. We hope to continue to contribute to sidekiq-rs as it seems now our destiny is intertwined ;)

Thanks! :heart:

**Comment by film42** [comment]
@jondot I've got a huge smile on my face right now. Thank you for choosing this crate and thanks for your contributions. Very cool framework. Can't wait to try it out :)
