### ISSUE TITLE
How to handle gracefull terminsation

### ISSUE THREAD

**Issue by georgeboot** [film42/sidekiq-rs#37]
I want to deploy a fleet of Sidekiq workers using Kubernetes, and want the instance count to scale automatically based on queue pressure.

In the current state of things, there is no way to tell the worker to stop taking on new work, finish what it's doing and then terminate. This functionality is also needed if the orchestrator (like k8s) decides it wants to run the pod somewhere else.

Without graceful termination, we could lose jobs because a worker took the work but didn't complete it.

Ideally there should be a way where the worker handles SIGNINT and once it received it, it stops taking on work, continues the process the on-hand work for a configurable duration, and then exits.

**Comment by film42** [comment]
The current version of `Processor::run()` looks like this:

```rust
    pub async fn run(self) {
        let cpu_count = num_cpus::get();

        // Start worker routines.
        for _ in 0..cpu_count {
            tokio::spawn({
                let mut processor = self.clone();

                async move {
                    loop {
                        if let Err(err) = processor.process_one().await {
                            error!("Error leaked out the bottom: {:?}", err);
                        }
                    }
                }
            });
        }

```

You can also call `process_one()` directly on the processor to build your own startup/ shutdown system. However, I think it would be nice for the crate to have something like this built in. The reason I haven't done yet is just lack of finding the right API.

The best pseudo code I can come up with would be like:

```rust
processor.run_with_options(
    RunOptions::default()
        // Start shutting down on this signal
        .shutdown_on_signal(&[SIGINT])
        // Wait up to 60 seconds before terminating
        .gaceful_shutdown_duration(Duration::from_secs(60)),
).await;
```

But it feels a little heavy. Thoughts?
